version: "3"

services:
  envoy:
    image: envoyproxy/envoy:dev-3f198ba35873bba736374ea568fcfa6c4d903215
    ports:
      - "80:80"
      - "9901:9901"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    restart: unless-stopped

  main_api_1:
    build:
      context: .
      dockerfile: dockerfile
    expose:
      - 1000
    environment:
      - PORT=1000
      - REDISLINK=redis://redis:6379
      - STORAGEADDR=minio
      - STORAGEPORT=9000
    depends_on: [redis]
    restart: unless-stopped

  main_api_2:
    build:
      context: .
      dockerfile: dockerfile
    expose:
      - 1000
    environment:
      - PORT=1000
      - REDISLINK=redis://redis:6379
      - STORAGEADDR=minio
      - STORAGEPORT=9000
    depends_on: [redis]
    restart: unless-stopped

  redis:
    image: "redis:alpine"
    command: redis-server --save "" --loglevel warning
    expose:
      - 6379
    volumes:
      - redis_data:/data
    restart: unless-stopped

  minio:
    image: minio/minio
    command: server /data
    expose:
      - 9000
      - 9001
    environment:
      MINIO_ROOT_USER: ${STORAGEACC}
      MINIO_ROOT_PASSWORD: ${STORAGEPWD}
      MINIO_CONSOLE_ADDRESS: ":9001"
      MINIO_SERVER_URL: http://${STORAGEDOMAIN}
    volumes:
      - storage_data:/data
    extra_hosts:
      # for local testing only, to avoid shadowing by container 'localhost' while console tries to lookup storage.localhost
      - "storage.localhost:host-gateway"
    restart: unless-stopped

volumes:
  storage_data:
  redis_data:
