global:
  scrape_interval:     1s


scrape_configs:
  - job_name: "apis"
    static_configs:
      - targets:
          - "main_api_1:1000"
          - "main_api_2:1000"

  - job_name: "envoy"
    metrics_path: /stats/prometheus
    static_configs:
      - targets:
          - "envoy:9901"