{
 "title": "Requests duration/count",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Req count rate 1m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(rest_response_time_duration_seconds_count[1m])"
    }
   ]
  },
  {
   "title": "Req duration rate 1m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(rest_response_time_duration_seconds_sum[1m])"
    }
   ]
  },
  {
   "title": "Req duration irate 1m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "irate(rest_response_time_duration_seconds_sum[1m])"
    }
   ]
  }
 ]
}